/**
 * Plugin SDK - Plugin Interfaces
 * All plugin type definitions
 */

// Detection Plugins
export {
  type DetectionPlugin,
  type YOLOConfig,
  type YOLODetectionPlugin,
  type CustomModelConfig,
  type CustomModelDetectionPlugin,
  type DetectionManifest,
  type DetectionProtocolConfig,
  type DetectionProtocolFrame,
  type DetectionProtocolCommand,
  type DetectionProtocolResponse,
  type DetectionPluginRegistry,
  createYOLOPlugin,
  createCustomModelPlugin,
} from './detectionPlugin';

// Mode Plugins
export {
  type ModePlugin,
  type ModeType,
  type RuleContext,
  type RuleAction,
  type ClassroomModeConfig,
  type ClassroomModePlugin,
  type AttendanceRecord,
  type ExamIntegrityConfig,
  type ExamIntegrityModePlugin,
  type ExamViolation,
  type SecurityModeConfig,
  type SecurityModePlugin,
  type SecurityThreat,
  type ZoneStatus,
  type FacilitySafetyConfig,
  type FacilitySafetyModePlugin,
  type PPEViolation,
  type HazardAlert,
  type ModeManifest,
  type ModePluginRegistry,
  createClassroomModePlugin,
  createExamIntegrityModePlugin,
  createSecurityModePlugin,
  createFacilitySafetyModePlugin,
} from './modePlugin';

// Alert Plugins
export {
  type AlertPlugin,
  type AlertChannel,
  type AlertResult,
  type AlertConnectionConfig,
  type TelegramAlertConfig,
  type TelegramAlertPlugin,
  type EmailAlertConfig,
  type EmailAlertPlugin,
  type SESAlertConfig,
  type SESAlertPlugin,
  type SNSAlertConfig,
  type SNSAlertPlugin,
  type WebhookAlertConfig,
  type WebhookAlertPlugin,
  type AlertManifest,
  type AlertPluginRegistry,
  createTelegramAlertPlugin,
  createEmailAlertPlugin,
  createSESAlertPlugin,
  createSNSAlertPlugin,
  createWebhookAlertPlugin,
} from './alertPlugin';

// Widget Plugins
export {
  type WidgetPlugin,
  type WidgetType,
  type WidgetRenderResult,
  type ChartWidgetConfig,
  type ChartWidgetPlugin,
  type TableWidgetConfig,
  type TableWidgetPlugin,
  type CounterWidgetConfig,
  type CounterWidgetPlugin,
  type AlertWidgetConfig,
  type AlertWidgetPlugin,
  type AlertStats,
  type MapWidgetConfig,
  type MapWidgetPlugin,
  type TimelineWidgetConfig,
  type TimelineWidgetPlugin,
  type CustomWidgetConfig,
  type CustomWidgetPlugin,
  type WidgetManifest,
  type WidgetPluginRegistry,
  createChartWidgetPlugin,
  createTableWidgetPlugin,
  createCounterWidgetPlugin,
  createAlertWidgetPlugin,
  createMapWidgetPlugin,
  createTimelineWidgetPlugin,
  createCustomWidgetPlugin,
} from './widgetPlugin';